version: 0.0
os: linux
files:
  - source: ./AMAZING-/dist
    destination: /var/www/html
    overwrite: yes

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: ubuntu
