version: 0.0
os: linux
files:
  - source: ./dist
    destination: /usr/share/nginx/html
    overwrite: yes

permissions:
  - object: /usr/share/nginx/html
    owner: root
    group: root
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: ubuntu
